version: "3.9"

services:
  web:
    image: fsconfig
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      -  redis-stack-server
    ports:
      - "127.0.0.1:8000:8000"
       
  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
  