version: "3.9"

services:
  fsconfig:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    
  redis:
    image: redis/redis-stack-server:latest
    ports:
        - "6379:6379"

  