version: "3.9"

services:
  fsconfig:
    image: fsconfig
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      -  redis-stack-server
    ports:
      - "127.0.0.1:8080:8080"

                    
  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
  